'use client'; 
// import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { usePathname } from "next/navigation";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const path = usePathname();

  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <nav className="site-navigation">
          <a className={`site-navigation__button ${(path === '/' ? `active` : ``)}`} href="/">Главная</a>
          <a className={`site-navigation__button ${(path === '/database' ? `active` : ``)}`} href="/database">База Данных</a>
        </nav>
        <main>{children}</main>
      </body>
    </html>
  );
}
